services:

  db:
    extends:
      file: docker-compose.common.yml
      service: db
    env_file:
        - ./.dev.env

  web:
    extends:
      file: docker-compose.common.yml
      service: web
    build:
      context: .
      dockerfile: ./dockerfiles/catalog3/Dockerfile
    env_file:
      - ./.dev.env
    volumes:
      - ./.dev.env:/code/.dev.env
