"""Device and MFP db models.

Revision ID: bfe9e86c6b60
Revises: bbaa014b9725
Create Date: 2024-05-24 15:35:21.238051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe9e86c6b60'
down_revision = 'bbaa014b9725'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
