"""Device inherited models fixes.

Revision ID: b1c446ddf584
Revises: e1d90ade417f
Create Date: 2024-06-10 16:13:37.535446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c446ddf584'
down_revision = 'e1d90ade417f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('cartridge_model_id', sa.Integer(), nullable=True))
    op.add_column('device', sa.Column('current_cartridge_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'device', 'model', ['cartridge_model_id'], ['id'])
    op.create_foreign_key(None, 'device', 'cartridge', ['current_cartridge_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.drop_column('device', 'current_cartridge_id')
    op.drop_column('device', 'cartridge_model_id')
    # ### end Alembic commands ###
