"""User model is_active field default to False.

Revision ID: bbaa014b9725
Revises: a9ebab5394ba
Create Date: 2024-05-06 15:24:52.853909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbaa014b9725'
down_revision = 'a9ebab5394ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
