"""Add MFPNetwork models fix.

Revision ID: aa8151204913
Revises: 629757a96656
Create Date: 2024-05-29 11:54:42.845595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa8151204913'
down_revision = '629757a96656'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_f_p_network',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('mfp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfp',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mac', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['device.id'], name='mfp_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='mfp_pkey')
    )
    op.drop_table('m_f_p_network')
    # ### end Alembic commands ###
