"""Model fixes

Revision ID: 629757a96656
Revises: 6391c1dd20f0
Create Date: 2024-05-29 11:36:42.965500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629757a96656'
down_revision = '6391c1dd20f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('m_f_p')
    op.alter_column('device', 'responsible_person_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('device', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('device', 'responsible_person_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('m_f_p',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mac', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['device.id'], name='m_f_p_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='m_f_p_pkey')
    )
    op.drop_table('mfp')
    # ### end Alembic commands ###
