"""MFP model.

Revision ID: e1d90ade417f
Revises: ac4b4504966b
Create Date: 2024-06-10 16:06:41.283455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d90ade417f'
down_revision = 'ac4b4504966b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
