"""Models fixes.

Revision ID: 5ed15d725d3f
Revises: b1c446ddf584
Create Date: 2024-06-11 10:08:14.612563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed15d725d3f'
down_revision = 'b1c446ddf584'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'is_original')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('is_original', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
