"""Some fixes.

Revision ID: 89a015a99910
Revises: 93d38c7d794d
Create Date: 2024-06-10 13:38:02.163644

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '89a015a99910'
down_revision = '93d38c7d794d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('mfp_network',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('mac', sa.String(), nullable=True),
    # sa.ForeignKeyConstraint(['id'], ['device.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.drop_table('cartridge')
    # op.drop_table('model')
    op.alter_column('device', 'vendor_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('room', 'building_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room', 'building_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('device', 'vendor_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.create_table('model',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text(
                        "nextval('model_id_seq'::regclass)"), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('vendor_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('is_original', sa.BOOLEAN(),
                              autoincrement=False, nullable=True),
                    sa.Column('original_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(
                        ['original_id'], ['model.id'], name='model_original_id_fkey'),
                    sa.ForeignKeyConstraint(
                        ['vendor_id'], ['vendor.id'], name='model_vendor_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='model_pkey'),
                    sa.UniqueConstraint('name', name='model_name_key'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('cartridge',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('model_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['id'], ['device.id'],
                                            name='cartridge_id_fkey'),
                    sa.ForeignKeyConstraint(
                        ['model_id'], ['model.id'], name='cartridge_model_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='cartridge_pkey')
                    )
    op.drop_table('mfp_network')
    # ### end Alembic commands ###
