"""Token and User relations.

Revision ID: 31a37d88f00c
Revises: 8eda930dc389
Create Date: 2024-04-27 19:16:31.783107

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '31a37d88f00c'
down_revision = '8eda930dc389'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key('token_user_id_fkey', 'token',
                          'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('token_user_id_fkey', 'token', type_='foreignkey')
    op.drop_column('token', 'user_id')
    # ### end Alembic commands ###
